def estadoRegiao(sigla):
    siglas ={
        "AC" : "NORTE",
        "AL" : "NORDESTE",
        "AP" : "NORTE",
        "AM" : "NORTE",
        "BA" : "NORDESTE",
        "CE" : "NORDESTE",
        "ES" : "SUDESTE",
        "GO" : "CENTRO-OESTE",
        "MA" : "NORDESTE",
        "MT" : "CENTRO-OESTE",
        "MS" : "CENTRO-OESTE",
        "MG" : "SUDESTE",
        "PA" : "NORTE",
        "PB" : "NORDESTE",
        "PR" : "SUL",
        "PE" : "NORDESTE",
        "PI" : "NORDESTE",
        "RJ" : "SUDESTE",
        "RN" : "NORDESTE",
        "RS" : "SUL",
        "RO" : "NORTE",
        "RR" : "NORTE",
        "SC" : "SUL",
        "SP" : "SUDESTE",
        "SE" : "NORDESTE",
        "TO" : "NORTE",
        "DF" : "DISTRITO FEDERAL",
    }
    return siglas.get(sigla, False)

def validaEstado(estado):
    estados = {
        "AC": True,
        "AL": True,
        "AP": True,
        "AM": True,
        "BA": True,
        "CE": True,
        "ES": True,
        "GO": True,
        "MA": True,
        "MT": True,
        "MS": True,
        "MG": True,
        "PA": True,
        "PB": True,
        "PR": True,
        "PE": True,
        "PI": True,
        "RJ": True,
        "RN": True,
        "RS": True,
        "RO": True,
        "RR": True,
        "SC": True,
        "SP": True,
        "SE": True,
        "TO": True,
        "DF": True,
    }
    return estados.get(estado, False)

def nomeEstado(sigla):
    siglaNomes = {
        "AC": "Acre",
        "AL": "Alagoas",
        "AP": "Amapá",
        "AM": "Amazonas",
        "BA": "Bahia",
        "CE": "Ceará",
        "ES": "Espírito Santo",
        "GO": "Goiás",
        "MA": "Maranhão",
        "MT": "Mato Grosso",
        "MS": "Mato Grosso do Sul",
        "MG": "Minas Gerais",
        "PA": "Pará",
        "PB": "Paraíba",
        "PR": "Paraná",
        "PE": "Pernambuco",
        "PI": "Piauí",
        "RJ": "Rio de Janeiro",
        "RN": "Rio Grande do Norte",
        "RS": "Rio Grande do Sul",
        "RO": "Rondônia",
        "RR": "Roraima",
        "SC": "Santa Catarina",
        "SP": "São Paulo",
        "SE": "Sergipe",
        "TO": "Tocantins",
        "DF": "Distrito Federal",
    }
    return siglaNomes.get(sigla, False)